name: 100-days-ci

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit pytest pytest-xdist[psutil] ruff

      - name: Run code sanity checks and fix issues.
        run: |
          ruff clean
          ruff check . --fix --config=pyproject.toml --output-format=github

      - name: Run unit tests
        run: |
          pytest -x -ra -q -n auto --dist worksteal --cache-clear